apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-devops-pipeline.secretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: "{{ include "azure-devops-pipeline.serviceAccountName" . }}" 
type: kubernetes.io/service-account-token