#https://raw.githubusercontent.com/kevchu3/azure-buildagent-container/refs/heads/main/resources/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-build-agent-openshift.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "azure-build-agent-openshift.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "azure-build-agent-openshift.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "azure-build-agent-openshift.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "azure_agent-source.imagestream" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "azure_agent-source.name" . }}
          - secretRef:
              name: azproxy
              optional: true
          ports:
          - containerPort: 8080
          securityContext:
            runAsUser: 1001
      serviceAccount: {{ template "azure-build-agent-openshift.serviceAccountName" . }}
      serviceAccountName: {{ template "azure-build-agent-openshift.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}