kind: Secret
apiVersion: v1
metadata:
  name: {{ include "azure_agent-source.name" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  AZP_POOL: "{{ .Values.azp_pool }}"
  AZP_TOKEN: "{{ .Values.azp_token }}"
  AZP_URL: "{{ .Values.azp_url }}"
type: Opaque
