{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "azure-build-agent-openshift.serviceAccountName" . }}
  labels:
{{ include "azure-build-agent-openshift.labels" . | indent 4 }}
{{- end -}}
